---
# tasks file for roles/deploy

# Deploy current tag?
# chown to www-data


- name: Messaging
  debug:
    msg: This is the end

- include_tasks:  deployment.yml
  loop: "{{ sites.values()|list }}"

- include_tasks:  vhost.yml
  loop: "{{ sites.values()|list }}"