- hosts: web
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ansible
  become: yes
  pre_tasks:
  handlers:
    - import_tasks: handler.yml

  roles:
    - apache
    - git
    

    #