all:
    vars:
      tier: ''
    hosts:
        
    children:
        test:
            hosts:
                ansible.intrepidea.com
        web:
            hosts:
                betvicweb2.royalroads.ca