---
# tasks file for deploy



# Check if composer is already installed
- name: Check if composer exists
  stat: "path=/usr/local/bin/composer"
  register: composer_exists
  tags:
    - host.install.composer

# Download Composer
- name: Download Composer
  when: not composer_exists.stat.exists
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
  tags:
    - download.composer
    - host.install.composer

# Globally install Composer
- name: Install Composer Globally
  when: not composer_exists.stat.exists
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  tags:
    - install.composer
    - host.install.composer
