---
# tasks file for roles/git

# Install Git
- name: Install Git
  apt:
    name: git
    state: present
  tags:
    - install.git
    - host.install.git


- name: Copy git deployment key
  copy:
    src: deployment_key
    dest: /home/ansible/.ssh/id_ecdsa
    decrypt: yes
    owner: ansible
    group: ansible
    mode: '0600'

#This might not belong here
- name: Set folder permissions on www
  file:
    path: /var/www
    owner: ansible
    group: www-data
    mode: 0775




   