##########################################################
# Royal Roads University Beta Tier Ansible Inventory
#
all:
    vars:
      tier: beta.
    children:
        drupal:
            children:
                school:
                misc:
        test:
            hosts:
                ansible.intrepidea.com
        school:
            hosts:
                betvicweb2.royalroads.ca
        misc:
            hosts:
                
        

          


               