##########################################################
# Royal Roads University Beta Tier Ansible Inventory
#
all:
    vars:
      tier: beta.
    hosts:
        
    children:
        test:
            hosts:
                ansible.intrepidea.com
        web:
            hosts:
                betvicweb2.royalroads.ca
            


               