---
- name: Install Settings File
  template:
    src: beta.settings.php.j2
    dest:  "/var/www/{{item.subdomain}}{{tier}}{{item.domain}}/web/sites/default/settings.php"
    owner: ansible
    group: www-data
    mode: '0644'
  when:  inventory_dir is  search ("beta")

    #
- name: Clear the cache
  command: vendor/bin/drush cc all
  args:
    chdir: "/var/www/{{item.subdomain}}{{tier}}{{item.domain}}"

    #
- name: Update DB
  command: vendor/bin/drush -y updatedb
  args:
    chdir: "/var/www/{{item.subdomain}}{{tier}}{{item.domain}}"

