---
- name: Extract Files
  unarchive:
    remote_src: yes
    src: /home/ansible/{{item.subdomain}}tar
    dest: /var/www/{{item.subdomain}}{{tier}}{{item.domain}}/web/sites/default/files/

- name: Recursively change ownership of a directory
  file:
    path: /var/www/{{item.subdomain}}{{tier}}{{item.domain}}/web/sites/default/files/
    state: directory
    recurse: yes
    owner: www-data
    group: www-data