---
# tasks file for roles/drupal

- name: Messaging
  debug:
    msg: This is the drupal role

- include_tasks:  config.yml
  loop: "{{ sites.values()|list }}"

- include_tasks: files.yml
  loop: "{{ sites.values()|list }}"